dictionary = {"India": "INR", "US": "USD", "Nepal": "NPR", "Bangladesh": "BDT"}
print("Dictionary :",dictionary)
print("\n1. copy() method")
dictCopy = dictionary.copy()
print("DictionaryCopy :", dictCopy)
print("\n2. key() method")
print("Keys of Dictionary :", dictionary.keys())
print("\n3. values() method")
print("Values of Dictionary :", dictionary.values())
print("\n4. get() method")
print("Get value of key - 'India' :", dictionary.get('India'))
print("\n5. pop() method")
dictionary.pop("US")
print("Dictionary after pop() :", dictionary)
print("\n6. popitem() method")
dictionary.popitem()
print("After popitem() :", dictionary)
print("\n7. items() method")
print("List of tuple of key-value pair :", dictionary.items())
print("\n8. update() method")
dictionary.update(dictCopy)
print("After updating Dictionary from DictCopy :", dictionary)
print("\n9. setdefault() method")
print("Value for key 'China' :", dictionary.setdefault("China", "CNY"))
print("\n10. clear() method")
dictionary.clear()
print("After clear() :", dictionary)